
spring:
  application:
    name: admin-server
server:
  port: 8933
eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://127.0.0.1:8769/eureka/  
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS